# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/authformdesgn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit


class Ui_AuthForm(object):
    def setupUi(self, AuthForm):
        AuthForm.setObjectName("AuthForm")
        AuthForm.resize(300, 226)
        AuthForm.setMaximumSize(300, 226)
        AuthForm.setMinimumSize(300, 226)
        self.centralwidget = QtWidgets.QWidget(AuthForm)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 241, 51))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 80, 241, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 20, 221, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QLineEdit.Password)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 140, 221, 23))
        self.pushButton.setObjectName("pushButton")
        AuthForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AuthForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 302, 21))
        self.menubar.setObjectName("menubar")
        AuthForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AuthForm)
        self.statusbar.setObjectName("statusbar")
        AuthForm.setStatusBar(self.statusbar)

        self.retranslateUi(AuthForm)
        QtCore.QMetaObject.connectSlotsByName(AuthForm)

    def retranslateUi(self, AuthForm):
        _translate = QtCore.QCoreApplication.translate
        AuthForm.setWindowTitle(_translate("AuthForm", "MainWindow"))
        self.groupBox.setTitle(_translate("AuthForm", "Логин"))
        self.groupBox_2.setTitle(_translate("AuthForm", "Пароль"))
        self.pushButton.setText(_translate("AuthForm", "Войти"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthForm = QtWidgets.QMainWindow()
    ui = Ui_AuthForm()
    ui.setupUi(AuthForm)
    AuthForm.show()
    sys.exit(app.exec_())